name = "neuralwired"
license = "MIT"
licenselink = "https://github.com/yourusername/hugo-theme-neuralwired/blob/master/LICENSE"
description = "A minimalist theme for neuralwired blog"
homepage = "https://github.com/yourusername/hugo-theme-neuralwired"
tags = ["blog", "minimal", "responsive"]
features = ["blog"]
min_version = "0.41.0"

[author]
  name = "neuralwired"
  homepage = "https://yourdomain.com"

[original]
  name = "neuralwired"
  homepage = "https://yourdomain.com"
